# Generated by Django 5.1.6 on 2025-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moduleinstance",
            name="professor",
        ),
        migrations.AddField(
            model_name="moduleinstance",
            name="professors",
            field=models.ManyToManyField(to="myapp.professor"),
        ),
    ]
