# Generated by Django 5.1.6 on 2025-02-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_module_module_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="module_code",
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name="professor",
            name="professor_code",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
